import Head from 'next/head';
import Sidbar from "../components/Sidbar";
import Feed from "../components/Feed";
import Wedgets from '../components/Wedgets';


export default function Home() {
  return (
    <div >
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen max-w-7xl mx-auto ">
          {/* slider */}
          <Sidbar />

          {/* feed */}
          <Feed />

          {/* widgest */}
          <Wedgets />


          {/* model */}

      </main>
      
      
     
    </div>
  )
}
