import Head from 'next/head';
import Sidbar from "../components/Sidbar";
import Feed from "../components/Feed";
import Wedgets from '../components/Wedgets';


export default function Home({newsResults,randomUsersResult}) {
  return (
    <div >
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen  mx-auto ">
          {/* slider */}
          <Sidbar />

          {/* feed */}
          <Feed />

          {/* widgest */}
          <Wedgets newsResults={newsResults.articles} randomUsersResult={randomUsersResult.results} />


          {/* model */}

      </main>
      
      
     
    </div>
  )
}


//https://saurav.tech/NewsAPI/top-headlines/category/bussiness/ir.json


export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res) => res.json());


  //how to hollow sections

  const randomUsersResult = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture"
  )
.then((res) => res.json());
  

  return {
    props: {
      newsResults,
      randomUsersResult
      
    },
  };
}
